apiVersion: v1
kind: Service
metadata:
  name: game-server
  labels:
    app: game-server
spec:
  type: NodePort
  selector:
    app: game-server
  ports:
    - port: 8080         # Cluster-internal port
      targetPort: 8080   # Container port
      nodePort: 30080    # External port on each node
      protocol: TCP
      name: http
